#%RAML 1.0 DataType
type: object
properties:
      street:
        type: string
      houseNumber?:
        type: number
      city:
        type: string
      country:
        type: string
      postalCode:
        type: string
